Update validate.yml

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -47,69 +47,66 @@ jobs:
       # Install required runtime modules
       #
 
-      - name: "Dependencies"
-        run: |
-          . .github/scripts/Install.ps1
-          Install-SourceModule -Repository "SomilGanguly/AzOps" -Branch "sogangul-AzOps-AddExtendedChildResources"
-          $module = Get-Module -Name AzOps -ListAvailable
-          $data = Import-PowerShellDataFile -Path $module.Path
-          foreach ($dependency in $data.RequiredModules) {
-              Install-Module -Name $dependency.ModuleName -RequiredVersion $dependency.RequiredVersion -Force
-          }
-        shell: pwsh
+      # - name: "Dependencies"
+      #   run: |
+      #     Install-Module -Name "AzOps" -Force
+      #   shell: pwsh
 
-      #
-      # Connect
-      # Authenticate Azure context
-      #
+      # #
+      # # Connect
+      # # Authenticate Azure context
+      # #
 
-      - name: "Connect"
-        shell: pwsh
-        run: |
-          $credential = New-Object PSCredential -ArgumentList $env:ARM_CLIENT_ID, (ConvertTo-SecureString -String $env:ARM_CLIENT_SECRET -AsPlainText -Force)
-          Connect-AzAccount -TenantId $env:ARM_TENANT_ID -ServicePrincipal -Credential $credential -SubscriptionId $env:ARM_SUBSCRIPTION_ID
-
+      # - name: "Connect"
+      #   shell: pwsh
+      #   run: |
+      #     $credential = New-Object PSCredential -ArgumentList $env:ARM_CLIENT_ID, (ConvertTo-SecureString -String $env:ARM_CLIENT_SECRET -AsPlainText -Force)
+      #     Connect-AzAccount -TenantId $env:ARM_TENANT_ID -ServicePrincipal -Credential $credential -SubscriptionId $env:ARM_SUBSCRIPTION_ID
+      - name: 'Run sharedsteps'
+        uses: ./.github/.templates/sharedSteps
       #
       # Diff
       # List index changes
       #
+      - name: 'Run validate deploy'
+        uses: ./.github/.templates/validate-deploy
+        
+      # - name: "Diff"
+      #   id: diff
+      #   shell: bash
+      #   run: |
+      #     if [ ! -z "$(git diff --name-status HEAD^ HEAD)" ]; then
+      #       echo $(git diff --name-status HEAD^ HEAD)
+      #       git diff --name-status HEAD^ HEAD > /tmp/diff.txt
+      #       if [ ! -z "$(git diff --diff-filter=D HEAD^ HEAD)" ]; then
+      #         echo $(git diff --diff-filter=D HEAD^ HEAD  --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r)
+      #         git diff --diff-filter=D HEAD^ HEAD --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r > /tmp/diffdeletedfiles.txt
+      #       fi
+      #     else
+      #       echo "The validation pipeline failed because there is currently no change to be processed"
+      #       exit 1
+      #     fi
 
-      - name: "Diff"
-        id: diff
-        shell: bash
-        run: |
-          if [ ! -z "$(git diff --name-status HEAD^ HEAD)" ]; then
-            echo $(git diff --name-status HEAD^ HEAD)
-            git diff --name-status HEAD^ HEAD > /tmp/diff.txt
-            if [ ! -z "$(git diff --diff-filter=D HEAD^ HEAD)" ]; then
-              echo $(git diff --diff-filter=D HEAD^ HEAD  --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r)
-              git diff --diff-filter=D HEAD^ HEAD --no-prefix | grep ^- | sed -r "s/^([^-+ ]*)[-+ ]/\\1/" | less -r > /tmp/diffdeletedfiles.txt
-            fi
-          else
-            echo "The validation pipeline failed because there is currently no change to be processed"
-            exit 1
-          fi
+      # #
+      # # Validate
+      # #
 
-      #
-      # Validate
-      #
-
-      - name: "Validate"
-        shell: pwsh
-        run: |
-          Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
-          Initialize-AzOpsEnvironment
-          $diff = Get-Content -Path /tmp/diff.txt
-          $module = Get-Module -Name AzOps
-          if(Test-Path -Path "/tmp/diffdeletedfiles.txt")
-          {
-            $diffdeletedfiles = Get-Content -Path /tmp/diffdeletedfiles.txt
-            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -DeleteSetContents $diffdeletedfiles -WhatIf })
-          }
-          else{
-            $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -WhatIf })
-          }
-          Get-Job | Remove-Job -Force
+      # - name: "Validate"
+      #   shell: pwsh
+      #   run: |
+      #     Import-PSFConfig -Path settings.json -Schema MetaJson -EnableException
+      #     Initialize-AzOpsEnvironment
+      #     $diff = Get-Content -Path /tmp/diff.txt
+      #     $module = Get-Module -Name AzOps
+      #     if(Test-Path -Path "/tmp/diffdeletedfiles.txt")
+      #     {
+      #       $diffdeletedfiles = Get-Content -Path /tmp/diffdeletedfiles.txt
+      #       $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -DeleteSetContents $diffdeletedfiles -WhatIf })
+      #     }
+      #     else{
+      #       $module.Invoke({ Invoke-AzOpsPush -ChangeSet $diff -WhatIf })
+      #     }
+      #     Get-Job | Remove-Job -Force
 
       #
       # Results
@@ -121,7 +118,7 @@ jobs:
           if [ -f /tmp/OUTPUT.md ]; then
             gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/OUTPUT.md
           else
-            echo "The output is not printed because file not exist"
+            echo "There are no results, so no comments are posted. For further information please look into the validate step."
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
